app/db/models/tour.py
from typing import Optional

from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String, Boolean

from app.db import Base


class Tour(Base):
    __tablename__ = "tours"

    id: Mapped[int] = mapped_column(primary_key=True)
    itinerary: Mapped[int] = mapped_column()
    price: Mapped[float] = mapped_column()
    duration: Mapped[int] = mapped_column()
    img_url: Mapped[Optional[str]] = mapped_column(String(), nullable=True)
    img_name_orig: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    img_name: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    is_reserved: Mapped[bool] = mapped_column(Boolean(), default=False)

    def __str__(self):
        return f"Тур {self.itinerary}"

app/__init__.py
from flask import Flask

from app.db import create_db
from app.routes.tour import tour_blueprint


app = Flask(__name__)
app.register_blueprint(tour_blueprint)


def main():
    create_db()
    app.run(debug=True, port=80)

app/db/__init__.py
from app.db.base import Session, Base, create_db
from app.db.models.tour import Tour

app/routes/tour.py
from uuid import uuid4
import random

from flask import Blueprint, render_template, redirect, url_for, request

from app.db import Tour, Session

tour_blueprint = Blueprint("tours", __name__)


@tour_blueprint.get("/")
def index():
    with Session() as session:
        tours = session.query(Tour).filter_by(is_reserved=False).all()
        random.shuffle(tours)
        return render_template("index.html", tours=tours)


@tour_blueprint.route("/add_tour/", methods=["GET", "POST"])
def add_tour():
    with Session() as session:
        if request.method == "POST":
            itinerary = request.form.get("itinerary")
            price = request.form.get("price")
            duration = request.form.get("duration")
            img_url = None
            img_name_orig = None
            img_name = None

            photo = request.files.get("photo")
            if photo and photo.filename:
                img_name_orig = photo.filename
                img_name = uuid4().hex + "." + img_name_orig.split(".")[-1]
                img_url = f"/static/img/{img_name}"
                photo.save("app" + img_url)

            tour = Tour(
                itinerary=itinerary,
                duration=duration,
                price=price,
                img_name=img_name,
                img_name_orig=img_name_orig,
                img_url=img_url
            )
            session.add(tour)
            session.commit()
            return redirect(url_for("tours.manage_tours"))

        return render_template("add_tour.html")


@tour_blueprint.get("/manage_tours/")
def manage_tours():
    with Session() as session:
        tours = session.query(Tour).all()
        return render_template("manage_tours.html", tours=tours)


@tour_blueprint.get("/delete/<int:id>/")
def delete_tour(id):
    with Session() as session:
        tour_instance = session.query(Tour).filter_by(id=id).first()
        if tour_instance:
            session.delete(tour_instance)
            session.commit()
        return redirect(url_for("tours.manage_tours"))


@tour_blueprint.route("/edit_tour/<int:id>/", methods=["GET", "POST"])
def edit_tour(id):
    with Session() as session:
        tour_instance = session.query(Tour).filter_by(id=id).first()

        if request.method == "POST" and tour_instance:
            tour_instance.itinerary = request.form.get("itinerary")
            tour_instance.duration = request.form.get("duration")
            tour_instance.price = request.form.get("price")
            tour_instance.is_reserved = True if request.form.get("is_reserved") else False

            photo = request.files.get("photo")
            if photo and photo.filename:
                tour_instance.img_name_orig = photo.filename
                tour_instance.img_name = uuid4().hex + "." + photo.filename.split(".")[-1]
                tour_instance.img_url = "/static/img/" + tour_instance.img_name
                photo.save("app" + tour_instance.img_url)

            session.commit()
            return redirect(url_for("tours.manage_tours"))

        return render_template("edit_tour.html", tour=tour_instance)


@tour_blueprint.get("/reserve/<int:id>/")
def reserve(id):
    with Session() as session:
        tour_instance = session.query(Tour).filter_by(id=id).first()
        if tour_instance:
            tour_instance.is_reserved = True
            session.commit()
        return render_template("reserved.html", tour=tour_instance)

app/templates/add_tour.html
{% extends "base.html" %}

{% block center %}
<form action="{{ url_for('tours.add_tour') }}" method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">маршрут туру</label>
        <input type="text" class="form-control" name="itinerary">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">тривалість</label>
        <input type="text" class="form-control" name="duration">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">ціна за тур</label>
        <input type="text" class="form-control" name="price">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">виберіть зображення туру</label>
        <input type="file" class="form-control" name="photo">
    </div>
    <button class="btn btn-success" type="submit">додати тур</button>
</form>
{% endblock center %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title %} Головна сторінка {% endblock title %}</title>
</head>
<body class="p-5 bg-primary-subtle">
    {% include "navigation.html" %}
    <br><br>
    {% block content %}
    {% endblock content %}

    <div class="container text-center">
        <div class="row">
            <div class="col">

            </div>
            <div class="col">
            {% block center %}
            {% endblock center %}
            </div>
            <div class="col">

            </div>
        </div>
    </div>
</body>
</html>

app/templates/edit_tour.html
{% extends "base.html" %}

{% block center %}
<form action="{{ url_for('tours.edit_tour', id=tour.id) }}" method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">маршрут туру</label>
        <input type="text" class="form-control" name="itinerary" value="{{ request.form.get('itinerary') or tour.itinerary }}">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">тривалість</label>
        <input type="text" class="form-control" name="duration" value="{{ request.form.get('floor') or tour.duration }}">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">ціна за тур</label>
        <input type="text" class="form-control" name="price" value="{{ request.form.get('price') or tour.price }}">
    </div>
    <div class="form-check form-switch">
    <input class="form-check-input" type="checkbox" role="switch" name="is_reserves" {% if tour.is_reserved %} checked {% endif %}>
    <label class="form-check-label" for="flexSwitchCheckChecked">зарезервований</label>
    </div>
    <div class="mb-3">
        <img src="{{ tour.img_url }}" class="d-block w-100">
        <label for="exampleFormControlInput1" class="form-label">виберіть зображення туру</label>
        <input type="file" class="form-control" name="photo">
    </div>
    <button class="btn btn-success" type="submit">Змінити тур</button>
</form>
{% endblock center %}

app/templates/index.html
{% extends "base.html" %}

{% block center %}
<div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-inner">

        {% for tour in tours %}
                <div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
                <img src="{{ tour.img_url }}" class="d-block w-100">
                <div class="carousel-caption d-none d-md-block">
                    <h5>{{ tour }}</h5>
                    <p>тривалість {{ tour.duration }}</p>
                    <p>ціна за тур {{ tour.price }}</p>
                </div>
                <a href="{{ url_for('tours.reserve', id=tour.id) }}" class="btn btn-info">Забронювати</a>
            </div>
        {% endfor %}

    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% endblock center %}

app/templates/manage_tours.html
{% extends "base.html" %}

{% block content %}
{% for tour in tours %}
    <div class="card" style="width: 18rem;">
    <img src="{{ tour.img_url }}" class="card-img-top">
        <div class="card-body">
            <h5 class="card-title">{{ tour }}</h5>
            <p class="card-text">тривалість: {{ tour.duration }}</p>
            <p class="card-text">Ціна: {{ tour.price }}</p>
            <p class="card-text">Зарезервований: {% if tour.is_reserved %} Так {% else %} Ні {% endif %}</p>
            <a href="{{ url_for('tours.edit_tour', id=tour.id) }}" class="btn btn-primary">Редагувати тур</a>
            <a href="{{ url_for('tours.delete_tour', id=tour.id) }}" class="btn btn-danger">Видалити тур</a>
        </div>
    </div>
{% endfor %}
{% endblock content %}

app/templates/navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <a href="{{ url_for('tours.index') }}" class="btn btn-info">Головна сторінка</a>
    <a href="{{ url_for('tours.manage_tours') }}" class="btn btn-info">Редагування туру</a>
    <a href="{{ url_for('tours.add_tour') }}" class="btn btn-info">Додати новий тур</a>
</nav>

app/templates/reserved.html
{% extends "base.html" %}

{% block center %}
<h1>Вітаємо! Ви успішно забронювали тур</h1>
<div class="card" style="width: 18rem;">
  <img src="{{ tour.img_url }}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">{{ tour }}</h5>
    <p class="card-text">Тривалість: {{ tour.duration }}</p>
    <p class="card-text">Ціна: {{ tour.price }}</p>
    <a href="{{ url_for('tours.index') }}" class="btn btn-primary">Повернутись на головну сторінку</a>
  </div>
</div>
{% endblock center %}